"""Constants for our integration."""

DOMAIN = "bq25895"

CONF_ADDR = "I2C_addr"
CONF_BUS = "I2C_bus"

DEFAULT_ADDR = "0x6A"
DEFAULT_BUS = "1"
DEFAULT_SCAN_INTERVAL = 60

CONF_MIN_BATTERY_VOLTAGE = "Min_batttery_voltage"
CONF_CHARGE_CURRENT_LIMIT = "Charge_current_limit"
CONF_CHARGE_VOLTAGE_LIMIT = "Charge_voltage_limit"
CONF_INPUT_CURRENT_LIMIT = "Input_current_limit"
CONF_PRECHG_CURRENT = "Prechg_current"
CONF_RECHARGE_THRESHOLD = "Recharge_threshold"
CONF_TERM_CURRENT = "Term_current"
CONF_THERMAL_THRESHOLD = "Thermal_threshold"

DEFAULT_MIN_BATTERY_VOLTAGE = 3.1
DEFAULT_CHARGE_CURRENT_LIMIT = 2.048
DEFAULT_CHARGE_VOLTAGE_LIMIT = 4.064
DEFAULT_INPUT_CURRENT_LIMIT = 1.15
DEFAULT_PRECHG_CURRENT = 0.128
DEFAULT_RECHARGE_THRESHOLD = 200
DEFAULT_TERM_CURRENT = 0.128
DEFAULT_THERMAL_THRESHOLD = 60